export enum MenuItemValue {
    address = 'address',
    home = 'home', 
    account = 'account', 
    wifi = 'wifi', 
    deviceManagement = 'deviceManagement', 
    guestAccess = 'guestAccess',
    vacationMode = 'vacationMode',
    energyRecommendations = 'energyRecommendations',
    worksWith = 'worksWith',
    security = 'security',
    notifications = 'notifications',
    manageDevices = 'manageDevices',
    loadPrioritization = 'loadPrioritization',
    outageHistory = 'outageHistory',
    advancedFeatures = 'advancedFeatures',
    appSettings = 'appSettings',
    helpSupport = 'helpSupport',
    feedback = 'feedback',
    logout = 'logout'
  }